[project]
name = "cnh-popular-ce-analise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1.0.1",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "streamlit>=1.45.1",
]
